language: node_js
 node_js: node
 cache:
   directories:
     - node_modules
 script:
   - npm test
 env:
   - CI=true

 before_deploy:
   - npm install netlify-cli -g
   - npm run build

 deploy:
   provider: script
   script: netlify deploy -s 61a566ea-ba4d-4806-91ca-107a628d2aa6 -t 7322d9dd1b6ab956db80ed1785eec87ca693e7482cbae14feb1f54e0934d222c -p ./build
   skip_cleanup: true
   on:
     branch: master